- name: base
  servo_config_file: servo_2_config.yaml
  joint_type: revolute
  pwm_pin: None
  min_angle: -90
  max_angle: 90
  initial_angle: 23.2
  initial_pwm: 1757
  initial_dh_dict:
      joint_angle: 0
      joint_distance: 5
      common_normal_length: 3
      link_twist_angle: 0

- name: shoulder 
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  pwm_pin: None
  min_angle: -90
  max_angle: 90
  initial_pwm: 1593
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 5
    common_normal_length: 3
    link_twist_angle: 0

- name: elbow
  servo_config_file: servo_1_config.yaml
  pwm_pin: None
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 1670
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 0
    common_normal_length: 0
    link_twist_angle: 0

- name: wrist
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 1657
  pwm_pin: None
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 0
    common_normal_length: 0
    link_twist_angle: 0

- name: gripper
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 1670
  pwm_pin: None
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 0
    common_normal_length: 0
    link_twist_angle: 0

