- name: base
  servo_config_file: servo_2_config.yaml
  joint_type: revolute
  pwm_pin: None
  min_angle: -90
  max_angle: 90
  initial_angle: 23.2
  initial_pwm: 1465
  initial_dh_dict:
    joint_angle: 60
    joint_distance: 5
    common_normal_length: 3
    link_twist_angle: 0
  max_motor_speed: 8


- name: shoulder 
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  pwm_pin: None
  initial_angle: 0
  min_angle: -90
  max_angle: 90
  initial_pwm: 1613
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 5
    common_normal_length: 3
    link_twist_angle: 0
  max_motor_speed: 8

- name: elbow
  servo_config_file: servo_1_config.yaml
  pwm_pin: None
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 763
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 5
    common_normal_length: 0
    link_twist_angle: 0
  max_motor_speed: 8

- name: wrist
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 1500
  pwm_pin: None
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 5
    common_normal_length: 0
    link_twist_angle: 0
  max_motor_speed: 8

- name: gripper
  servo_config_file: servo_1_config.yaml
  joint_type: revolute
  min_angle: -90
  max_angle: 90
  initial_angle: 0
  initial_pwm: 1500
  pwm_pin: None
  initial_dh_dict:
    joint_angle: 0
    joint_distance: 6
    common_normal_length: 0
    link_twist_angle: 0
  max_motor_speed: 8
  

