---
servo_name: servo_4
servo_type: HS-422
degrees_of_movement: 180
duty_cyle_ms: 20
max_angle_duty_cycle_ms: 2.5
max_degree_value: 90
min_angle_duty_cycle_ms: 0.5
min_degree_value: -90
torque: None
volts: 5
pin_out: 4
...
